Fixed audio file requirements
teslamotors/light-show pull request #51
Opened 2022-10-21 10:19 UTC by spaceXrace

Added audio file requirements, because 48Mhz files aren't played in sync with the light show.

Issue has been discussed [here](https://www.reddit.com/r/TeslaLightShow/comments/rrmrce/music_and_lights_out_of_sync/ )

2022-10-21 19:48 UTC, JVB-Tesla requested changes

2022-10-21 19:48 UTC, JVB-Tesla commented on README.md
> +Make sure the file is encoded with a sample rate of 44.1Mhz; less common 48Mhz files won't properly sync to the light show.
Should be kHz not Mhz.
And add a space between the number and unit (e.g., 44.1 kHz) and we can merge this documentation update.

2022-10-23 14:38 UTC, spaceXrace reviewed
Sorry right, fixed it!

2022-11-01 00:15 UTC, JVB-Tesla approved these changes

2022-11-01 21:52 UTC, merged

2022-11-03 07:55 UTC, Nice7118 commented
stop.listening to joseph samudio!!! he is stealing money from tesla !!!

On Tue, Nov 1, 2022, 4:52 PM JVB-Tesla ***@***.***> wrote:

> Merged #51 <https://github.com/teslamotors/light-show/pull/51> into
> master.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/teslamotors/light-show/pull/51#event-7717469497>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A27YIT3RID3NOHWJWW3ERPTWGGGJNANCNFSM6AAAAAARLAYMFQ>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>